### ISSUE TITLE
minus number bug

### ISSUE THREAD

**Issue by rsy56640** [rsy56640/Mini_C#2]
input:   
```
-23 + -7 + -2.4
```
program terminates at: `lexer.cpp namespace::supporters::rIsInUnminusableSituation`
```
  bool rIsInUnminusableSituation(vector<token_t> &r) {
            auto&& rb = r.back();         <==== r.size() == 0   // line: 82 (maybe not exactly later)
```

**Comment by rsy56640** [comment]
`23+ -4` is tokenized as `23(i32)`, `+`, `4(i32)`

**Comment by ssyram** [comment]
fixed.

**Comment by rsy56640** [comment]
`a->_b = A::_a  - 0x123 +0x1A;` is not invalid.   
`a->_b = A::_a  + 0x123 +0x1A;` is ok.
